//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace GR.Entity
{

    /// <summary>
    /// 角色按钮权限关联表
    /// </summary>
    [JsonObject(MemberSerialization.OptIn), Table(Name = "sys_role_button")]
    public partial class SysRoleButton
    {

		[JsonProperty, Column(DbType = "varchar(36)", IsPrimary = true)]
		public string Id { get; set; }

		[JsonProperty, Column(Name = "Button_Id", DbType = "varchar(36)")]
		public string ButtonId { get; set; }

		[JsonProperty, Column(Name = "Create_By", DbType = "varchar(50)")]
		public string CreateBy { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty, Column(Name = "create_on", DbType = "datetime", ServerTime = DateTimeKind.Utc, CanUpdate = false)]

		public DateTime? CreateOn { get; set; }
		/// <summary>
		/// 更新时间
		/// </summary>
		[JsonProperty, Column(Name = "update_on", DbType = "timestamp", ServerTime = DateTimeKind.Utc)]
		public DateTime? UpdateOn { get; set; }

		[JsonProperty]
		public string Remark { get; set; }

		[JsonProperty, Column(Name = "Role_Id", DbType = "varchar(36)")]
		public string RoleId { get; set; }

		[JsonProperty, Column(Name = "Update_By", DbType = "varchar(50)")]
		public string UpdateBy { get; set; }








		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
