//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace GR.Entity {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "sys_role_user")]
	public partial class SysRoleUser {

		[JsonProperty, Column(Name = "Create_By")]
		public string CreateBy { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty, Column(Name = "create_on", DbType = "datetime", ServerTime = DateTimeKind.Utc, CanUpdate = false)]

		public DateTime? CreateOn { get; set; }
		/// <summary>
		/// 更新时间
		/// </summary>
		[JsonProperty, Column(Name = "update_on", DbType = "timestamp", ServerTime = DateTimeKind.Utc)]
		public DateTime? UpdateOn { get; set; }

		[JsonProperty, Column(DbType = "varchar(40)")]
		public string Id { get; set; }

		[JsonProperty, Column(Name = "Role_Id", DbType = "varchar(40)")]
		public string RoleId { get; set; }

		[JsonProperty, Column(Name = "Update_By", DbType = "varchar(40)")]
		public string UpdateBy { get; set; }



		[JsonProperty, Column(Name = "User_Id", DbType = "varchar(40)")]
		public string UserId { get; set; }


		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
