//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace GR.entity {

	/// <summary>
	/// 文件
	/// </summary>
	[JsonObject(MemberSerialization.OptIn), Table(Name = "tb_file")]
	public partial class TbFile {

		/// <summary>
		/// 主键
		/// </summary>
		[JsonProperty, Column(Name = "id", DbType = "varchar(36)", IsPrimary = true)]
		public string Id { get; set; }

		/// <summary>
		/// 授权类型（公开，部分可见，不给谁看）
		/// </summary>
		[JsonProperty, Column(Name = "authtype", DbType = "varchar(20)")]
		public string Authtype { get; set; }

		/// <summary>
		/// 创建人
		/// </summary>
		[JsonProperty, Column(Name = "create_by", DbType = "varchar(50)")]
		public string CreateBy { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty, Column(Name = "create_on", DbType = "datetime")]
		public DateTime? CreateOn { get; set; }

		/// <summary>
		/// 目录id
		/// </summary>
		[JsonProperty, Column(Name = "directory_id", DbType = "varchar(36)")]
		public string DirectoryId { get; set; }

		/// <summary>
		/// 下载(后台guid)名称
		/// </summary>
		[JsonProperty, Column(Name = "download_name", DbType = "varchar(50)")]
		public string DownloadName { get; set; }

		/// <summary>
		/// 文件名称
		/// </summary>
		[JsonProperty, Column(Name = "file_name", DbType = "varchar(100)")]
		public string FileName { get; set; }

		/// <summary>
		/// 服务器文件路径
		/// </summary>
		[JsonProperty, Column(Name = "local_dic", DbType = "varchar(500)")]
		public string LocalDic { get; set; }

		/// <summary>
		/// 备注
		/// </summary>
		[JsonProperty, Column(Name = "remark")]
		public string Remark { get; set; }

		/// <summary>
		/// 共享文件
		/// </summary>
		[JsonProperty, Column(Name = "shared", DbType = "tinyint(4)")]
		public sbyte? Shared { get; set; }

		/// <summary>
		/// 大小(单位kb)
		/// </summary>
		[JsonProperty, Column(Name = "size", DbType = "double(11,2)")]
		public double? Size { get; set; }

		/// <summary>
		/// 状态(0正常-1删除1禁用)
		/// </summary>
		[JsonProperty, Column(Name = "state")]
		public int? State { get; set; }

		/// <summary>
		/// 更新人
		/// </summary>
		[JsonProperty, Column(Name = "update_by", DbType = "varchar(50)")]
		public string UpdateBy { get; set; }

		/// <summary>
		/// 更新时间
		/// </summary>
		[JsonProperty, Column(Name = "update_on", DbType = "timestamp")]
		public DateTime? UpdateOn { get; set; }


		#region 外键 => 导航属性，ManyToMany

		#endregion
	}

}
